-- 1ST TABLE
CREATE SEQUENCE ID_SEQ
START WITH 105
INCREMENT BY 1;
CREATE TABLE LOC_TABLE(
    ID NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50),
    LOCATION VARCHAR2(50)
);

INSERT INTO LOC_TABLE VALUES(ID_SEQ.NEXTVAL, 'ARTI', 'BHATPARA');
INSERT INTO loc_table VALUES (id_seq.NEXTVAL, 'Subhendu', 'Narayanpara');
INSERT INTO loc_table VALUES (id_seq.NEXTVAL, 'Kaushik', 'Naihati');
INSERT INTO loc_table VALUES (id_seq.NEXTVAL, 'Ram', 'Kolkata');

CREATE TABLE TOUR(
    TOUR_ID VARCHAR2(4) PRIMARY KEY,
    TOUR_SPOT VARCHAR2(50),
    FARE NUMBER(50),
    TYPES VARCHAR2(10)

);

INSERT INTO tour VALUES ('T1','Gangtok',6000,'Delux');
INSERT INTO tour VALUES ('T2','Puri',2000,'General');
INSERT INTO tour VALUES ('T3','Nainital',9000,'Delux');
INSERT INTO tour VALUES ('T4','Andaman',12000,'General');

CREATE VIEW TOURVIEW AS
SELECT TOUR_SPOT, FARE FROM TOUR WHERE TYPES='Delux';
